### ISSUE TITLE
bot.editSelf not working

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [fuwwy/moonstone#11]
I was trying to change my bot's username with `bot.editSelf`, but it doesn't change the username of the bot. My code below.
![carbon](https://user-images.githubusercontent.com/70828596/118346505-f8e4a800-b509-11eb-840e-b489a793b58e.png)
If you need more info then let me know.

**Comment by itsfolf** [comment]
You're trying to change the username while the bot isn't ready or even connected.
