### ISSUE TITLE
I'm Dumb and need help

### ISSUE THREAD

**Issue by Darker-Ink** [fuwwy/moonstone#14]
I'm trying to make it when a user requests to speak it makes them a speaker so far I got this but I get a error

bot.on("handRaised", async (user, room) => {
  console.log(user.username);
  console.log(room.name)
	let role = 'speaker'
    room.setRole(role, user)
});

**Comment by itsfolf** [comment]
Use ActiveUser#setAsSpeaker
https://moonstone.folf.party/#/main/main/class/ActiveUser?scrollTo=setAsSpeaker

**Comment by Darker-Ink** [comment]
oh ty was about to close it because just saw you had a support server
