### ISSUE TITLE
dogehouse will be closing soon

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [fuwwy/moonstone#15]
@fuwwy I just watched ben awad's (The owner of dogehouse) dogehouse log, and in the video he will be stopping the production of dogehouse. This is just to let people know that are working on moonstone the news. [Link](https://youtu.be/I8PkQgPiSq8) to Ben's video to learn more.

**Comment by SourCreamCulture** [comment]
@Isaiah-Hamilton The community is picking up the project so dogehouse is not actually being stopped. Ben Awad is done with it, but now the community is picking it up and keeping it alive. The new community repo location is https://github.com/dogehousetv/dogehouse so @fuwwy you can keep this api wrapper alive :)

**Comment by Isaiah-Hamilton** [comment]
I'm so happy that the community is picking up the project. And continuing to work on it.
