### ISSUE TITLE
add moderation capabilities

### ISSUE THREAD

**Issue by SourCreamCulture** [fuwwy/moonstone#5]

**Comment by itsfolf** [comment]
What are you looking for, exactly?

**Comment by SourCreamCulture** [comment]
like being able to add people as a speaker and making people mod. Being able to ban people from chat and other stuff.

**Comment by itsfolf** [comment]
Changing speaker/listener status is already a thing.
Added auth levels @ https://github.com/fuwwy/moonstone/commit/7f4a5ab0ca29d81fc3b347bc7718c7dc583c230b

Will work on banning next

**Comment by SourCreamCulture** [comment]
It there a way to make it so I can make the bot accept people to be speakers?

**Comment by itsfolf** [comment]
rip
