### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by SourCreamCulture** [fuwwy/moonstone#8]
can you show an example for how to change the bots profile?

**Comment by itsfolf** [comment]
For example, `bot.editSelf({bio: "New bot bio"})`

https://github.com/fuwwy/moonstone/blob/7f4a5ab0ca29d81fc3b347bc7718c7dc583c230b/index.d.ts#L56-L62

**Comment by Isaiah-Hamilton** [comment]
> can you show an example for how to change the bots profile?

This is a good issue. I tried to make an example file for how to change your profile settings, but couldn't find a way to use the username in the export class User in `lib/core/User.js`. edit now I see what I was doing wrong.

**Comment by SourCreamCulture** [comment]
Thanks for the example! :)

**Comment by jzeuzs** [comment]
@fuwwy Why not close this? 🤔

**Comment by Isaiah-Hamilton** [comment]
pull request #10 fixes this issue and future issues on how to use Moonestone and should be closed. @fuwwy

**Comment by itsfolf** [comment]
[editSelf](https://moonstone.folf.party/#/main/main/class/Moonstone?scrollTo=editSelf)
